# platform :ios, '12.0'

target 'HRForecast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HRForecast
      pod 'Charts'
      pod 'Alamofire'
      pod 'SwiftyJSON'
      pod 'Firebase/Analytics'
      pod 'Firebase/Database'
    
end
